services:
  couchbase:
    image: couchbase:enterprise-7.6.1
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    volumes:
      - couchbase-data:/opt/couchbase/var
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/pools"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: ndolestudio/httpmock:latest
    ports:
      - "80:8000"
      - "443:8443"
    env_file: .env
    depends_on:
      couchbase:
        condition: service_healthy
    volumes:
      - ./certs:/app/certs

volumes:
  couchbase-data:
