services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8000"
      - "443:8443"
    env_file: .env
    volumes:
      - /etc/letsencrypt/live/httpmock.dev:/app/certs
