services:
  api:
    image: ndolestudio/httpmock:latest
    ports:
      - "80:8000"
      - "443:8443"
    env_file: .env
    logging:
      driver: "gcplogs"
      options:
        gcp-project: "httpmock-dev"
    volumes:
      - ./certs:/app/certs
